version: "3.8"

services:
  server:
    build:
      context: ./server
    container_name: tls_server
    ports:
      - "8443:8443"
    environment:
      - SSLKEYLOGFILE=/tmp/sslkey.log
    networks:
      default:
        aliases:
          - server

  client:
    build:
      context: ./client
    container_name: python_client
    environment:
      - SSLKEYLOGFILE=/tmp/sslkey.log
    depends_on:
      - server
    networks:
      default:
        aliases:
          - client
    volumes:
      - ./sslkey.log:/tmp/sslkey.log  # <--- Mount key log file to the host
