Version: "3.8"
services:
  server:
    build:
      context: ./server
    container_name: tls_server
    ports:
      - "8443:8443"
    networks:
      default:
        aliases:
          - server
  client:
    build:
      context: ./client
    container_name: python_client
    depends_on:
      - server
    networks:
      default:
        aliases:
          - client

